# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: games CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-frontend:

    runs-on: self-hosted

    steps:
    - run: whoami
    - run: nvm use 18.12.1
    - run: cd games-frontend && yarn install
    - run: yarn run build
