# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: games CI

defaults:
  run:
    shell: bash -ieo pipefail {0}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-frontend:

    runs-on: self-hosted
    
    defaults:
      run:
        working-directory: ./games-frontend
        shell: bash -ieo pipefail {0}

    steps:
    - uses: actions/checkout@v3
    - name: Check NodeJS
      run: ls -lah && nvm use 18.12.1
    - name: Install packages
      run: cd games-frontend && yarn install
    - name: Run build
      run: cd games-frontend && yarn run build
    - name: Syncing folders
      run: rsync -av --progress --delete dist/ ~/sites/games.spa/
    - name: Restart web-server
      run: sudo systemctl restart nginx
